version: '3.4'

services:

  home-assistant:
    image: homeassistant/raspberrypi3-homeassistant:0.89.1
    hostname: home-assistant
    ports:
      # Home Assistant unencrypted TCP 8123
      - mode: host
        target: 8123
        published: 8123
        protocol: tcp
    networks:
      - home-assistant-net1
    volumes:
      - type: bind
        source: /opt/homeassistant
        target: /config
    deploy:
      labels:
        local.description: "Home Assistant"
      restart_policy:
        condition: on-failure

networks:
  home-assistant-net1:
